Add new `Performance/BlockGivenWithExplicitBlock` cop
rubocop-hq/rubocop-performance pull request #173
Opened 2020-09-25 08:41 UTC by fatkodima

This cop identifies unnecessary use of a `block_given?` where explicit check of block argument would suffice.

```ruby
# bad
def method(&block)
  do_something if block_given?
end

# good
def method(&block)
  do_something if block
end
```

### Benchmark
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  gem 'benchmark-ips'
end

def if_block(&block)
  if block
  end
end

def if_block_given(&block)
  if block_given?
  end
end

Benchmark.ips do |x|
  x.report('if block')         { if_block }
  x.report('if block_given?')  { if_block_given }
  x.compare!
end
```

### Results
```
Warming up --------------------------------------
            if block     1.039M i/100ms
     if block_given?   844.838k i/100ms
Calculating -------------------------------------
            if block     10.382M (± 1.1%) i/s -     51.960M in   5.005227s
     if block_given?      8.443M (± 1.1%) i/s -     42.242M in   5.003794s

Comparison:
            if block: 10382417.4 i/s
     if block_given?:  8443073.9 i/s - 1.23x  (± 0.00) slower
```

2020-10-02 01:47 UTC, marcandre commented
Oh, cool, I had to do just that for `ostruct` and was wondering if that would trigger block capturing or not (and be slower). Glad it doesn't.

I'd mark the autocorrection as unsafe, even it's quite unlikely to be:
```ruby
def foo(&block)
  block ||= ->(x) { ...}
  warn "Using default ..." unless block_given?
  foo(&block)
end
```

2020-10-02 08:00 UTC, fatkodima commented
Good point. Updated to not trigger an offense when the block arg is reassigned.

2020-10-16 04:40 UTC, koic approved these changes

2020-10-16 05:08 UTC, marcandre requested changes

2020-10-16 05:08 UTC, marcandre commented on lib/rubocop/cop/performance/block_given_with_explicit_block.rb
> +          block_arg_name = block_arg.source[1..-1].to_sym
Use `loc.name.source`; your expression isn't reliable in the unlikely scenario `def foo(&    block)`

2020-10-16 05:08 UTC, marcandre commented on lib/rubocop/cop/performance/block_given_with_explicit_block.rb
> +        def reassigns_block_arg?(def_node, block_arg_name)
Alternative (only if you prefer)
```ruby
def_node_matcher, :reassigns_block_arg?, '`(lvasgn %1 ...)'
```

2020-10-16 05:10 UTC, marcandre commented
Sorry I forgot to check this. Don't hesitate to ping me after 2-3 days.

2020-10-16 11:46 UTC, fatkodima commented
Updated.

2020-10-16 14:21 UTC, marcandre approved these changes
LGTM 👍

2020-10-17 15:17 UTC, merged

2020-10-17 15:17 UTC, koic commented
Thanks!